---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/glossary
  label: Glossary
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/recommendations
  label: Recommendations
  create: all
  match: "**/*"
- type: directory
  path: content/guides
  label: Guides
  create: all
  match: "**/*"
- type: directory
  path: content/classes
  label: Classes
  create: all
  match: "**/*"
- type: directory
  path: content/links
  label: Links
  create: all
  match: "**/*"
- type: directory
  path: content/forms
  label: Forms
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/publications
  label: Publications
  create: all
  match: "**/*"
- type: directory
  path: content/packages
  label: Packages
  create: all
  match: "**/*"
- type: directory
  path: content/presentations
  label: Presentations
  create: all
  match: "**/*"
- type: directory
  path: content/documents
  label: Documents
  create: all
  match: "**/*"
- type: directory
  path: content/newsletters
  label: Newsletters
  create: all
  match: "**/*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content/deals
  label: Deals
  create: all
  match: "**/*"
- type: directory
  path: content/updates
  label: Updates
  create: all
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/specials
  label: Specials
  create: all
  match: "**/*"
- type: directory
  path: content/terms
  label: Terms
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.6
